### PR TITLE
remove cuda 8.0.27, there is newer version in tree

### PR DESCRIPTION
**Pull request by mpkh**

### CODE REVIEW

**Comment by mpkh** [comment]
no, in-tree version is missing gcc 5.4 allowing patch

**Comment by sjnewbury** [comment]
Okay.  I'll leave it in there for now.  I've been having a go at getting the GCC NVPTX offloading working, what in here right now isn't complete, I have more to commit, but I haven't been able to test it because I discovered my NVIDIA hardware isn't new enough (only Kepler and later is supported; whilst I have only Tesla and Fermi).  Are you able or interested in doing so if I push what I have?

**Comment by mpkh** [comment]
@sjnewbury sry I've fixed in tree version, please feel free to remove this version

**Comment by mpkh** [comment]
@sjnewbury I don't have very new nvidia either, maximum Tesla and Titan...

**Comment by sjnewbury** [comment]
Actually, I believe it should work fine with the Titan.

**Pull request merged**
