### PR TITLE
New ebuild media-libs/libplacebo

### PR DESCRIPTION
**Pull request by haasn**
A library for GPU-based image rendering. This is a new optional
dependency of VLC 3.0.0.

It's worth pointing out that we could also host a clone of the `media-video/vlc-3.0.0` ebuild that replaces the `--disable-libplacebo` by a new USE flag, optional dependency and conditional enable. Do you think this is worth doing?

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
Please run "repoman" to check your ebuild. The LICENSE should be "LGPL-2.1+" in order to match the corresponding file in "/usr/portage/licenses/".

I'm working on a vlc-3.0.0 ebuild in my personal overlay. Ping me when this ebuild is added here and I'll add the corresponding USE flag.

**Comment by haasn** [comment]
Thanks for pointing that out. I've pushed a fix to the license and also the copyright year.

Repoman still gives me the following errors:

```
  IUSE.invalid [fatal]          4
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: shaderc
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: vulkan
   media-libs/libplacebo/libplacebo-9999.ebuild: shaderc
   media-libs/libplacebo/libplacebo-9999.ebuild: vulkan
```

Not sure what this is about. I guess it's maybe about lack of documentation, but surely at least "vulkan" is an officially sanctioned USE flag somewhere?

```
  dependency.bad [fatal]        26
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome/systemd)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome/systemd)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma/systemd)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma/systemd)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/developer)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/developer)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/no-multilib)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/no-multilib)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(default/linux/amd64/17.0/systemd)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/systemd)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64/no-multilib)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64/no-multilib)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64/no-multilib/selinux)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64/no-multilib/selinux)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: DEPEND: ~amd64(hardened/linux/amd64/selinux)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
   media-libs/libplacebo/libplacebo-0.4.0.ebuild: RDEPEND: ~amd64(hardened/linux/amd64/selinux)
[     'dev-util/shaderc[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]']
```
I don't understand these errors at all.

```
  metadata.missing [fatal]      1
   media-libs/libplacebo/metadata.xml
```
This I could do, if you think it's needed. (I noticed e.g. the `shaderc` or `vulkan-loader` ebuilds do not provide a metadata.xml either)

**Comment by stefantalpalaru** [comment]
You need to add a "metadata.xml" file and describe your non-global USE flags in it. It looks something like this: https://github.com/stefantalpalaru/gentoo-overlay/blob/master/net-wireless/cubicsdr/metadata.xml

The dependency errors mean that your ebuild supports architectures on which one or more of your dependencies are not available. In your specific case, you have one keyworded ebuild (libplacebo-0.4.0) depending on a package that only provides a live ebuild (so it's not keyworded) - "shaderc".

You can either create a stable "shaderc" ebuild, or ignore the error.

> (I noticed e.g. the shaderc or vulkan-loader ebuilds do not provide a metadata.xml either)

They should.

**Comment by haasn** [comment]
Okay. I've added a metadata.xml. I've also added a `REQUIRED_USE` to make sure users don't end up with a configuration that doesn't make sense.

In case you're wondering, the reason `shaderc` is a separated USE flag from `vulkan` is because other things may depend on `shaderc` support in the future (for example d3d11, although I'm not sure how relevant that is to gentoo-gpu), and we may also allow other SPIR-V compilers in the future as well, too.

In theory, you could also use libplacebo with vulkan support enabled but shaderc support disabled, if all you care about are simple blitting and other basic rendering that doesn't require the use of shaders, but it's an obscure use case.

But that said, it might be a better idea to just have the `vulkan` USE flag and model shaderc as an optional dependency that we pull in whatever configurations it makes sense, rather than as a USE flag that users have to manually enable.

**Comment by haasn** [comment]
It's worth pointing out that in the meantime I've submitted an [updated PR against the official gentoo repo](https://github.com/gentoo/gentoo/pull/10006), with various changes (newer libplacebo version, new USE flags).

It looks like things are progressing there (with some roadblocks that still need to be resolved), so it's your call: Either you could cherry-pick the ebuild from that PR, or just revert this commit.

**Comment by sjnewbury** [comment]
As I mentioned I'm going to try to do a better job of keeping things up to date, and I suppose I should also do a proper job with metadata etc...  Meanwhile, I'll give you commit access, so you can decide for yourself.

**Comment by haasn** [comment]
Seems like upstream is being a bit sluggish here, so I've decided to push an up-to-date version to this overlay in the meantime, so that users of your overlay don't end up trying to compile using an outdated ebuild and run into errors.

**Pull request merged**
